### ISSUE TITLE
Update Hero Image for 2022

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#1]
From @yarnetsky in Slack...

> Idea for front page image — I'm probably biased as a native Buffalonian, but I think the city flag is super cool. For the front page splash image, I'd love to incorporate the flag's lightning bolts and stars faded in the background behind a photo of Canalside or the Buffalo skyline. The bolts reflects Buffalo's status at the forefront of electricity. In 1896 Nikola Tesla helped make Buffalo the first electrified city in the world.

Opening this issue to begin the discussion around the hero image for 2022. As Jerry has expressed interest in the splash image, I'm assigning this issue to him. If you have a suggestion or an image to use, please share.

**Comment by dzoladz** [comment]
I really like the feeling of the state flag's lightning bolts and stars rising in the background of the cityscape. As you hinted at, incorporating text into the image might make it a little too busy and detract from the overall uniqueness of the hero. What do others think?

**Comment by yarnetsky** [comment]
I concur on 1 and 3 are the best fits design-wise (and make Buffalo look the best). Unfortunately, the visitors center didn't have a photo of Main St from the theater district. Still, because the Buffalo sign would be very cool I'm going to reach out in one more place.

**Comment by yarnetsky** [comment]
Yep, that's clear. As soon as I get the bugs worked out on my new M1 Apple laptop I'll dig in on it.
