### ISSUE TITLE
speaker images on presentation layout

### ISSUE THREAD

**Issue by phette23** [code4lib/2022.code4lib.org#112]
We should either 1) omit the `image_src` for speakers who do not have an image, then use the `placeholderImage` JS function to insert a randomly chosen nopic image programmatically, or 2) randomly assign all the speakers different nopic images in the speakers.yml file. Right now, everyone uses the same nopic0.jpg, but if we delete all their `image_src` attributes then the speaker images on the presentation pages break (because do not use the same include as the speakers/index page and assume that everyone has an `image_src`).

Personally, I lean towards having random, different nopics in the speakers data because it seems simpler and not like much extra work, but I could go either way. Not a lot of point if working on this before we get the images we do have added.

**Comment by metageeky** [comment]
I think I can edit my code to handle that situation. is there an easy way to test for existence of a variable in Fluid?

**Comment by dzoladz** [comment]
I believe you can do:
```
{% if variable_name %}
   do some stuff
{% endif %}
```

**Comment by metageeky** [comment]
Yep. Had to test a few things to make sure it worked.

**Comment by dzoladz** [comment]
> We should either 1) omit the image_src for speakers who do not have an image, then use the placeholderImage JS function to insert a randomly chosen nopic image programmatically

Closing, as this functionality should now be available on `/speakers`, `/workshops`, and `/schedule`
