### ISSUE TITLE
Schedule loading method (scroll) prevents keyboard navigation via links

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2022.code4lib.org#149]
The current way that the schedule loads on the page prevents users from navigating this page via links, as the content of the page is not fully loaded.

For example, on https://2022.code4lib.org/schedule/day-1/, navigating with the tab key goes to "Opening Keynote", then jumps to the day selector at the bottom of the page, instead of going to the first talk in Group 1 (because that content isn't loaded until you scroll down to it).

**Comment by phette23** [comment]
We should just load the whole timeline immediately instead of on scroll. I've never looked at this page's code but I did wonder why we're doing that, seems more complicated for no good reason.
