### ISSUE TITLE
Venue image alt text should describe link location

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2022.code4lib.org#151]
On https://2022.code4lib.org/general-info/venues/ there is an image of the venue which is a link. If it's important this is kept as a link, then the alt text of the image should convey where this link will take the user. However, this link is also included in the "Website" text below the image, so the image likely doesn't need to be a link.

**Comment by phette23** [comment]
I'd be fine with just removing the link around the image, it's not clear where you expect it to go even for visual users.

**Comment by kaitlinnewson** [comment]
That makes sense to me as well - I can work on this issue.
