### ISSUE TITLE
Sponsorship Update - March 30

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#170]
All logos have been added to the google drive.

Developers for Diversity - Bronze - https://github.com/pulibrary
University at Buffalo Libraries - Scholarship - https://library.buffalo.edu/
University of Michigan - Bronze & Scholarship - https://www.lib.umich.edu/
Penn State University Libraries - Bronze & Scholarship - https://libraries.psu.edu/

**Comment by phette23** [comment]
#172 closes this
