### ISSUE TITLE
Add 1 new person to Speakers page and talk

### ISSUE THREAD

**Issue by librarianchase** [code4lib/2022.code4lib.org#179]
Relaying from Program Committee: Please add Bryan Hayley to the Speakers page.

He will be co-presenting with Amy Jiang in the "Converting Excel Files into XML: Two ways explained" talk.

Her previous co-presenter withdrew.

**Comment by phette23** [comment]
@librarianchase do you have the biographical information for Bryan Hayley? We usually have at least an institution and position, but we also look for pronouns, a bio paragraph, a speaker image, and [image alt text](https://2022.code4lib.org/forms/alt-collection.html).

Let us know about that and then we will work on adding them.

**Comment by librarianchase** [comment]
@phette23 Working on that...The Program Committee chair sent Bryan the links to the Speaker Consent Form and the image submission form for the website...let me check with him to see if he has heard back from Bryan. Thanks!

**Comment by phette23** [comment]
@librarianchase any update on this speaker's info? If not, we might just add an empty profile for now to have something in place.

**Comment by librarianchase** [comment]
@phette23 I was out of town for a bit and am catching up now...Program chair sent me the following:

Name: Bryan Haley
Email: bryan.haley@laverne.edu
Institution: University of La Verne
Position: Student Worker, Software Developer
Bio: no bio submitted
Pronouns: he/him
