### ISSUE TITLE
New list of scholarship winners

### ISSUE THREAD

**Issue by Blake-** [code4lib/2022.code4lib.org#191]
Bios & Social Media for Scholarship Winners

 

Erika Barber 
Twitter handle: @ErikaGBarber

David Broom
 
Tiffany Cheung
 
Hyung Wook Choi 

Chanda Hardin 
Chanda is the Library Technician for the National Museum of African American History and Culture Museum at the Smithsonian Institution where she co-leads the Content Support Group for the Smithsonian Libraries and Archives User Experience Program. She has a graduate certificate in Instructional Technology Integration from the University of Maryland Global Campus and she looks forward to learning more about how she can contribute fruitfully to Code4Lib’s vibrant and diverse community.

Twitter handle: @BiblioOsmosis

Soojeong Herring 
My name is Soojeong Herring, and I am acquisitions and cataloging specialist at Colorado State University Libraries. I am so happy to be in the community, and I look forward to learning a lot of things and meeting you all at the conference!

Jalesia Horton 
Jalesia Horton is the Director of Access and Resource Sharing Services at Southern Methodist University. She received her MLIS in May 2017 and is expected to complete her Master's in Public Administration in 2022.Her work focuses on increasing access to academic libraries through innovative and updated services, user design, web design, and increased accessibility options for those with disabilities. 

Twitter handle: @jalesia

Faezeh Jahanshiri 
My name is Faezeh Jahanshiri. I am a librarian, and work at the Central Library of Rochester. I’m very interested in computer programming and computer science, in-general, for instructional and educational purposes. I began studying computer programming a few years ago when I was attending the school of information at the San Jose State University in California while I was in the library & information science master’s program. I completed a few computer programming courses and continued learning on my own after I graduated in 2018. I have been presenting Python programming classes at the Central Library of Rochester since October 2021.These courses are designed for absolute beginners and provide a gateway to coding and programming to help them build a strong foundation in computer programming. The objective is to provide a stepping stone for library patrons of all ages who are interested in learning the basics of coding to break into the world of coding and encourage them to explore many career possibilities in the coding field. 

Twitter handle: @FJpari01

Chenyue Jiao 
As a third-year doctoral student in Library and Information Science at the University of Illinois Urbana Champaign, Chenyue's research focuses on issues in scholarly communication. Her research agenda is to understand how libraries provide better services and make right decisions for users in a big data era. She is excited to be selected as a 2022 Code4Lib scholarship recipient because of the connections and collaborations with the Code4Lib community.

Twitter handle: @chenyuej

Dr Raj Kumar

Grace Liu 
Grace Liu is a Systems Librarian and Engineering Liaison at University of Windsor Leddy Library. She holds a Master of Computer Science and an MLIS degree. Her research interests include library technology, electronic resources management, and library services to international students.

Meng Qu
Meng is a Web Services Librarian from the Miami University - Oxford, Ohio. Her interest of coding front-end websites has never stopped since years ago. She has recently turned her research interests into big data, data analysis, and Machine Learning, with the goal of building better library services.

Jhani Miller 

Joah Tang 
Joah Tang is a Youth Services and Makerspace Library Assistant for the Tompkins County Public Library. He runs TCPL's children's robotics club, teen robotics club, and young adult makerspace programs. Joah is a self-taught coder, hobby roboticist, and lifelong library lover.

**Comment by dzoladz** [comment]
Do we anticipate any additional biographical details coming in from the scholarship winners over the next few days? Or, should we go ahead and publish what we have to the conference site?

**Comment by Blake-** [comment]
None that I know of
