### ISSUE TITLE
Add Community Support Volunteer Details

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#193]
Just opening this issue to exchange info and such

**Comment by phette23** [comment]
Working on this on draft PR #200.

**Comment by metageeky** [comment]
Alt texts:

-Andromeda Yelton: "A smiling white woman with glasses, rosy cheeks, and curly brown hair. She's in three-quarter profile, looking at the camera like she's definitely up to something."
- Tess Grynoch: "Tess Grynoch, a white woman with short brown curly hair, smiling and proudly wearing her UMass Chan Medical School, Lamar Soutter Library sweater."

@phette23 What's the best way to get you the images?

**Comment by metageeky** [comment]
* Bobbi Fox: "A smiling large old white woman with glasses and long brown/grey hair."
