### ISSUE TITLE
Add The DPOE-N Funding option.

### ISSUE THREAD

**Issue by Blake-** [code4lib/2022.code4lib.org#207]
We were thinking it could go under General Info – Scholarships – Additional Funding.  Natalie gave us permission to use the image.
The information went out on the listserv etc, so we thought this would be another good place to share it.

 This is the text:

 

Digital Preservation Outreach and Education Network (DPOE-N) funding for USA citizens and residents

 

![image](https://user-images.githubusercontent.com/5229940/166452100-bccb8b2a-6287-4150-97d6-65508d03680b.png)

 

We are thrilled to let you know of a new funding opportunity we’ve just learned about for attending Code4Lib 2022! The DPOE-N (Digital Preservation Outreach & Education Network) has funding left for this academic year. They are willing to support attendees of the Code4Lib Conference. The maximum amount is $2,500 for each application. If you are considering coming to Buffalo for to the conference next month, but funding has been an issue, please consider applying. 

 

NOTES: 

Even if you have already registered and paid for everything yourself, you can STILL apply for the funding. Once your application is approved, you will be reimbursed for your costs. 
The total processing time is about 4 - 6 weeks. 
Only U.S. citizens and residents can apply. You will need to submit a W-9 form for income tax purposes. 
For more information and to submit an application for funding, please visit: [https://www.dpoe.network/professional-development-support/]( You can directly contact DPOE-N (Natalie Baur: [nbaur@pratt.edu](mailto:nbaur@pratt.edu)) with any questions.

**Comment by dzoladz** [comment]
If there are no objections, I'm fine with adding this info. Should it be placed directly underneath this year's recipients list?

**Comment by Blake-** [comment]
I think that works? I'm not sure of the best place, but whatever everyone thinks looks good is fine.
