### ISSUE TITLE
Nov. 29th: Close - Accept Pre-Conference Proposals

### ISSUE THREAD

**Issue by phette23** [code4lib/2022.code4lib.org#21]
(from pre-conf committee email on Oct. 27th)

> We are taking proposals until November 18, 2021, 5 PM PST / 8 PM EST.

**Comment by dzoladz** [comment]
Announced via email:
> The deadline for pre-conference proposals... has been extended to November 29th, 5 PM PST / 8 PM EST.

We'll need to update any scheduled PRs.
