### ISSUE TITLE
Please delete speaker and talk from Day 2

### ISSUE THREAD

**Issue by librarianchase** [code4lib/2022.code4lib.org#247]
Please delete our no-show speaker and talk when you get the chance:

Kaci Resau
Turnover Blues - The Need for Succession Planning for Technical Library Positions

Thanks!

**Comment by phette23** [comment]
I have time for this tomorrow too @dzoladz if you don't get to it.

**Comment by phette23** [comment]
Wait you already did this! Closing 🙂
