### ISSUE TITLE
Update Venue Information (Awaiting Planning Committee)

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#3]
There are two possible locations for the May conference: North Campus and Downtown. A final decision on the location for the Buffalo conference has not yet been reached.

Once we have a definitive location, we'll need to populate the venue information in `data/conf.yml`

**Comment by Blake-** [comment]
@dzoladz Sorry, still not settled. We have a meeting Thursday this week and I'll let you know what's up.

**Comment by Blake-** [comment]
Hosting in Jacobs School of Medicine and Biomedical Sciences (JSMBS)

**Comment by dzoladz** [comment]
Closing, as the conversation continues in #96
