### ISSUE TITLE
Header says we're an online conference after the date

### ISSUE THREAD

**Issue by yarnetsky** [code4lib/2022.code4lib.org#42]
Shall we pull the word "Online" in the header and leave just the date as was prior practice (2020 and before)?

If we're going to be hybrid then "live and online" might be worth noting, but otherwise saying online might mislead.

**Comment by dzoladz** [comment]
I'm going to merge some code to remove the "Online" designation in the jumbotron as a quick fix. This is related to both #8, #41, and some less-than-ideal implementation for last year's online-only conference.

**Comment by phette23** [comment]
So if I understand right this refers to the jumbotron include: https://github.com/code4lib/2022.code4lib.org/blob/main/_includes/homepage/jumbotron.html#L21-L23

The `if site.data.conf.venue.name != nil` (possibly added by Derek's commit above?) check should ensure that this doesn't display except when the conference is actually online. So I think we can close this one but will wait for Jerry to confirm.

**Comment by dzoladz** [comment]
No comments or activity for 2 months. Closing this one.
