### ISSUE TITLE
Mention Ruby/Dev Minimum Requirements in README

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#49]
If our site requires a minimum version of Ruby, we should mention that in the README.md file.

From Slack:
> Probably mention needing Ruby 2.6 at least. Jekyll doesn't work with Ruby 3 either.

> In fact, at least 2.6.3 per this site saying "Ruby 2.6.3 includes a version of RubyGems that’s less strict, so upgrading Ruby will automatically upgrade RubyGems and should fix the issue too."

**Comment by phette23** [comment]
I thought a bit about this last night and was thinking maybe from the readme we should link to a wiki page with "known working configurations" and where to go to get help if you still cannot build the site. I'm on ruby 2.5.7 and it's working, so I don't necessarily think ruby version is a strict limitation, there are probably several factors and rather than spend a lot of time identifying them we could just list our various setups and how we got the site to build.

**Comment by metageeky** [comment]
Well, that narrows it down a bit. Ruby 2.5.1 was not sufficient. But yes, known working configurations is a good idea and perhaps limitations like how Jekyll currently doesn't support Ruby 3 (at least according to what I read while debugging my build yesterday).

**Comment by phette23** [comment]
Created a [Known Working Configurations](https://github.com/code4lib/2022.code4lib.org/wiki/Known-Working-Configurations) wiki page and added my own.

**Comment by phette23** [comment]
@jerryyarnetsky Derek said you might have an Apple M1 laptop? And/or a windows machine? If you have the site building on either of those could you add an overview of how you got it working to the wiki page I linked in my last comment?

**Comment by yarnetsky** [comment]
Lately I've been using a Github Codespaces VM. I did get it to build on Windows by adding a couple more gems. Never got it to run on my M1 due to gems unavailable for the arm chip. I'll double check everything on Monday or Tuesday (I have some urgent grading to knock out) and will add my configs.

**Comment by dzoladz** [comment]
Installed `rbenv` this evening and successfully built the site using Ruby 3.0.0 on macOS Big Sur.
```
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

**Comment by dzoladz** [comment]
Updated the wiki with a direct link to the build configurations that are known to work
