### ISSUE TITLE
Add 2 new sponsors & prospectus edit

### ISSUE THREAD

**Issue by phette23** [code4lib/2022.code4lib.org#55]
See comments in Slack this morning:

> Please add the following to the sponsor page:
> Balsamiq Studios LLC- https://balsamiq.com/wireframes/ - Captioning Sponsor - logo in google drive.
> Western New York Library Resources Council - http://www.wnylrc.org/ - Contributor Sponsor - Logo in google drive.

Images Drive folder: https://drive.google.com/drive/folders/1sA8D47Ig1MSUpHnbDBi13OKEFuhlYRvK

**Comment by mjingle** [comment]
@phette23 Also, don't forget to reduce by one for the number of available Captioning sponsors in the prospectus. <goes back to lurking in the bushes.>

**Comment by phette23** [comment]
One more edit:

> Could the following please be added to the https://2022.code4lib.org/prospectus/ page - right above the Sponsor Code4Lib 2022? Text to add “A one-page information sheet (PDF) is available to assist with making a case to sponsor the Code4Lib Conference.” Here is the link to the PDF - https://drive.google.com/file/d/11oFZcxx5F_gCdkJ5S7WIzUom-AkNxuAM/view?usp=sharing

**Comment by phette23** [comment]
If no one gets to this today (Monday), I have a better shot at working on it tomorrow.

**Comment by dzoladz** [comment]
I can take of this one right now
