### ISSUE TITLE
Create 2022 Skeleton Schedule

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#76]
Per Kathy Azevedo in Slack:

> Can someone get a skeleton schedule posted on the Schedule page? You can use the [https://2020.code4lib.org/schedule/](https://2020.code4lib.org/schedule/) and the following details as a guide. The descriptions under each of the headers listed on the 2020 site, can be reused from for this year’s conference.
> * Monday, May 23 - 9am-5pm - Preconference Workshops (Minor Modification from 2020's description - “Preconference details **will be** available …”
> * Tuesday, May 24 - 9am - 5:15pm - General Conference, Day One
> * Wednesday, May 25 - 9am - 5:15pm - General Conference, Day Two
> * Thursday, May 26 - 9am - 12:45pm - General Conference, Day Three

**Comment by dzoladz** [comment]
@starsplatter Is this a task that's in your wheelhouse? And, something that you'd have time to complete over the next week?

**Comment by starsplatter** [comment]
Yup!

**Comment by dzoladz** [comment]
Thank you!

**Comment by dzoladz** [comment]
How's this one going? Any updates/ETA? Anything that you need help with?

**Comment by starsplatter** [comment]
Working on it this weekend, sorry, I didn't intend for it to take so long!
