### ISSUE TITLE
How would you like Keynote speaker images and bios?

### ISSUE THREAD

**Issue by bibliotechy** [code4lib/2022.code4lib.org#81]
The Keynote committee has images and bios for the two keynote speakers that will shortly be announced. What's the best way for me to provide a the images and bio? Happy to make a PR, but I didn't see an obvious existing template to update. JUst let me know whatever makes your lives easier.

**Comment by dzoladz** [comment]
You can send the images and bios to derekz@ohionet.org. It will only take me a few minutes to have them published to the website. Send my thanks to the Keynote Committee for their work on the selections this year.
