### ISSUE TITLE
Open call for posters

### ISSUE THREAD

**Issue by phette23** [code4lib/2022.code4lib.org#87]
See the email to the listserv from this morning.

> Proposals can be submitted through Friday, February 21, 2022 at 11:59pm PST (GMT−8). Voting (if needed) will start on March 7, 2022 and continue through March 18, 2022. The URL to submit votes will be announced on the Code4Lib mailing list. The final list of posters will be announced at the end of March.
> Submit your poster proposal! <https://forms.gle/ELyF1dx6U3FnvZoU7>

**Comment by kaitlinnewson** [comment]
I can take this one if no one is working on it.
