### ISSUE TITLE
Hosting in Jacobs School of Medicine and Biomedical Sciences

### ISSUE THREAD

**Issue by Blake-** [code4lib/2022.code4lib.org#96]
I think for here:
https://github.com/code4lib/2022.code4lib.org/blob/main/_data/conf.yml#L58
Hosting in Jacobs School of Medicine and Biomedical Sciences (JSMBS), 
JSMBS 2120A&B for most of the events and then 2nd floor Atrium South for things like lunch and posters. 

https://medicine.buffalo.edu/about/our_campuses.html
Jacobs School Of Medicine And Biomedical Sciences
University in Buffalo, New York
955 Main St, Buffalo, NY 14203

**Comment by phette23** [comment]
We'll want an image of the building for the venue section. See 2020 as an example: https://2020.code4lib.org/general-info/venues/

**Comment by Blake-** [comment]
There's a couple places passed along to me.

1. There's a ton here: https://ubphoto.smugmug.com/keyword/Jacobs%20School%20of%20Medicine%20Biomedical%20Sciences/
2. And here is a nice bunch
https://www.buffalo.edu/administrative-services/managing-facilities/planning-designing-and-construction/building-profiles/profile-host-page.host.html/content/shared/university/page-content/facilities/955mai.detail.html
